### ISSUE TITLE
Fullscreen mode breaks history function

### ISSUE THREAD

**Issue by joergludwig** [tudorilisoi/ep_fullscreen#1]
Hi,

first of all thank you for your great plugin!

We noticed, that the history function of etherpad does not work in fullscreen mode correctly:
1. The background color of the history text is not set, so you can see the underlying web site.
2. You cannot disable fullscreen mode after leaving the history.

**Comment by tudorilisoi** [comment]
You need to style the history div with CSS, and there may be a javascript error
I'm not using history, nor do I have the needed time to handle this problem. Sorry.

**Comment by joergludwig** [comment]
Solution:

1.
Add the following line to src/static/css/timeslider.css:
#padmain { background-color: white; }

2.
When exiting the history function etherpad reinitializes ep_fullscreen and all variables get lost. I modified index.js to use css classes to switch to fullscreen mode. That way we do not need any internal state anymore. Patch is attached.
[index.js.txt](https://github.com/tudorilisoi/ep_fullscreen/files/33044/index.js.txt)
