### ISSUE TITLE
Fullscreen functionality attached to div #editorcontainerbox

### ISSUE THREAD

**Issue by KimBrodowski** [tudorilisoi/ep_fullscreen#5]
In it's current version the fullscreen toggle event is not only attached to the fullscreen button, but also to the div `#editorcontainerbox`.

This is odd since you'll be able to toggle fullscreen by clicking the right side of the toolbar for example. Reviewing the code I assume this is unintended behaviour.

I've fixed this in #4.

**Comment by SiebelsTim** [comment]
Is merged in #4. Can be closed.
